import { PaperNote } from '../types';

export function generateMarkdown(paper: PaperNote): string {
  return `---
title: "${paper.title.replace(/"/g, '\\"')}"
authors: "${paper.authors.replace(/"/g, '\\"')}"
venue: "${paper.venue.replace(/"/g, '\\"')}"
year: ${paper.year}
doi: "${paper.doi}"
category: "${paper.category}"
tags: [${paper.tags.map(t => `"${t}"`).join(', ')}]
status: "${paper.status}"
rating: ${paper.rating} / 5
updatedAt: "${paper.updatedAt}"
---

# ${paper.title}

> **저자**: ${paper.authors || '미지정'}  
> **게재지/연도**: ${paper.venue || '미지정'} (${paper.year || '미지정'})  
> **DOI / 링크**: [${paper.doi || '링크 없음'}](${paper.doi || '#'})  
> **연구 분야**: ${paper.category || '미지정'} | **태그**: ${paper.tags.map(t => `#${t}`).join(' ')}

---

## 1. 연구 목적 (Objective)
${paper.objective || '*(작성된 내용 없음)*'}

---

## 2. 연구 방법 (Methodology)
${paper.methodology || '*(작성된 내용 없음)*'}

---

## 3. 연구 결과 (Results)
${paper.results || '*(작성된 내용 없음)*'}

---

## 4. 한계점 (Limitations)
${paper.limitations || '*(작성된 내용 없음)*'}

---

## 5. 내 생각 & 아이디어 (My Thoughts)
${paper.myThoughts || '*(작성된 내용 없음)*'}

---
*기록일: ${new Date(paper.createdAt).toLocaleDateString('ko-KR')} | 최근 수정: ${new Date(paper.updatedAt).toLocaleDateString('ko-KR')} - Generated by PaperNote*
`;
}

export function downloadMarkdown(paper: PaperNote): void {
  const md = generateMarkdown(paper);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const safeTitle = paper.title.replace(/[^a-zA-Z0-9가-힣_-]/g, '_').slice(0, 40) || 'paper_note';
  a.href = url;
  a.download = `[PaperNote]_${safeTitle}_${paper.year || ''}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateBibtex(paper: PaperNote): string {
  if (paper.bibtex && paper.bibtex.trim().length > 10) {
    return paper.bibtex.trim();
  }
  const firstAuthor = (paper.authors.split(',')[0] || 'author').trim().split(' ').pop()?.toLowerCase() || 'unknown';
  const citeKey = `${firstAuthor}${paper.year || new Date().getFullYear()}${paper.title.split(' ')[0]?.toLowerCase() || 'paper'}`;
  return `@article{${citeKey},
  title     = {${paper.title}},
  author    = {${paper.authors}},
  journal   = {${paper.venue}},
  year      = {${paper.year}},
  url       = {${paper.doi}}
}`;
}

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text).then(() => true).catch(() => false);
  } else {
    // Fallback
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textArea);
    return Promise.resolve(success);
  }
}
